apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-go-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-go
      tier: backend
  template:
    metadata:
      labels:
        app: rest-go
        tier: backend
    spec:
      containers:
      - name: go-app-docker
        image: ciulik/go-app-docker
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe: 
          httpGet:
              port: 8080
          periodSeconds: 10
          initialDelaySeconds: 5