apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-backend-api-ingress
spec:
  rules:
  - http:
      paths:
      - path: /events
        pathType: Prefix
        backend:
          service:
            name: my-backend-api
            port:
              number: 8080
      - path: /events/:id
        pathType: Prefix
        backend:
          service:
            name: my-backend-api
            port:
              number: 8080
      - path: /events/:id/register
        pathType: Prefix
        backend:
          service:
            name: my-backend-api
            port:
              number: 8080
      - path: /signup
        pathType: Prefix
        backend:
          service:
            name: my-backend-api
            port:
              number: 8080
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: my-backend-api
            port:
              number: 8080
